# Generated by Django 5.1.2 on 2024-10-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Url',
        ),
    ]
