# Generated by Django 5.1.2 on 2024-11-05 01:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlbot', '0004_remove_todolist_user_todolist_user_id_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created_at'], 'verbose_name': '待辦事項', 'verbose_name_plural': '待辦事項列表'},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='name',
        ),
        migrations.AddField(
            model_name='todolist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('pending', '未完成'), ('completed', '完成')], default='pending', max_length=20, verbose_name='待辦事項狀態'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='待辦事項名稱'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='user_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Line用戶ID'),
        ),
    ]
