# Generated by Django 5.1.2 on 2025-03-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlbot', '0005_alter_todolist_options_remove_todolist_create_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['created_at'], 'verbose_name': '待辦事項', 'verbose_name_plural': '待辦事項列表'},
        ),
    ]
